### INSTALLATION & IMPORTING

In [2]:
import pandas as pd

In [3]:
pd.__version__

'3.0.6'

### SERIES - 1D DATA

In [4]:
# Create a series from a list

scores = pd.Series([85,92,78,95,88])
scores

0    85
1    92
2    78
3    95
4    88
dtype: int64

In [5]:
# Series with custom index

scores = pd.Series([85,92,78,95,88], index=["Hafiy", "Hanna", "Hadif", "Hayyan", "Husna"])
scores
print(scores["Hadif"])

78

In [6]:
# Series from a dictionary

data = {
    "Yusuf": 99,
    "Yasmin": 100,
    "Qafiy": 98
}
scores = pd.Series(data)
print(scores["Yusuf"])

99

### DATAFRAME - 2D TABLE

In [7]:
# Create a DataFrame from a dictionary

data = {
    "Name": ["Irham", "Hadif", "Iskandar", "Qazif"],
    "Age": [25,30,40,55],
    "Scores": [85,92,78,95]
}

df = pd.DataFrame(data)
df

       Name  Age  Scores
0     Irham   25      85
1     Hadif   30      92
2  Iskandar   40      78
3     Qazif   55      95

In [8]:
# Explore the DataFrame

df.shape
df.dtypes
df.head()
df.tail(3)

       Name  Age  Scores
1     Hadif   30      92
2  Iskandar   40      78
3     Qazif   55      95

### READING FILES - CSV & EXCEL

In [9]:
# Read a CSV file
df = pd.read_csv("./data_f/students.csv")
df
df.head(14)

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance
0,101,Ali Khan,22,Male,Mumbai,Python,88.0,Yes,95
1,102,Sara Mehta,25,NaN,Delhi,Data Science,92.0,Yes,98
2,103,John D'souza,21,Male,Bangalore,Python,55.0,No,72
3,104,Mia Sharma,28,Female,Mumbai,Machine Learning,76.0,Yes,85
4,105,Rahul Verma,23,Male,Pune,Data Science,45.0,No,60
5,106,Priya Nair,26,Female,Chennai,Python,91.0,Yes,99
6,107,Tom Wilson,24,Male,Delhi,Machine Learning,67.0,Yes,78
7,108,Neha Gupta,22,Female,Bangalore,Data Science,83.0,Yes,90
8,109,Arjun Rao,27,Male,Hyderabad,Python,72.0,Yes,82
9,110,Sneha Joshi,21,Female,Mumbai,Machine Learning,NaN,No,55
10,111,Karan Patel,29,Male,Pune,Data Science,95.0,Yes,97
11,112,Divya Singh,24,Female,Chennai,Python,61.0,Yes,74
12,113,Anil Kumar,23,Male,Delhi,Machine Learning,79.0,Yes,88
13,114,Pooja Reddy,25,Female,Hyderabad,Data Science,50.0,No,65

In [10]:
# Read an Excel file

df1 = pd.read_excel("./data_f/pandas_tutorial.xlsx", sheet_name="Sales")
df1
df1.shape
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SaleID       10 non-null     int64
 1   SalesPerson  10 non-null     str
 2   Region       10 non-null     str
 3   Product      10 non-null     str
 4   Quantity     10 non-null     int64
 5   UnitPrice    10 non-null     int64
 6   TotalSale    10 non-null     int64
 7   Month        0 non-null      float64
dtypes: float64(1), int64(4), str(3)
memory usage: 772.0 bytes

In [11]:
# Save to CSV

data = {
    "Name": ["Irham", "Hadif", "Iskandar", "Qazif"],
    "Age": [25,30,40,55],
    "Scores": [85,92,78,95]
}

df = pd.DataFrame(data)
df

#df.to_csv("output.csv")
df.to_csv("./data_f/output_data.csv")
df.to_csv("./data_f/output_data_1.csv", index=False)
df.to_json("./data_f/output_data_2.json")

### SELECTING DATA

In [12]:
# Select a single column

df = pd.read_csv("./data_f/students.csv")
df

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance
0,101,Ali Khan,22,Male,Mumbai,Python,88.0,Yes,95
1,102,Sara Mehta,25,NaN,Delhi,Data Science,92.0,Yes,98
2,103,John D'souza,21,Male,Bangalore,Python,55.0,No,72
3,104,Mia Sharma,28,Female,Mumbai,Machine Learning,76.0,Yes,85
4,105,Rahul Verma,23,Male,Pune,Data Science,45.0,No,60
5,106,Priya Nair,26,Female,Chennai,Python,91.0,Yes,99
6,107,Tom Wilson,24,Male,Delhi,Machine Learning,67.0,Yes,78
7,108,Neha Gupta,22,Female,Bangalore,Data Science,83.0,Yes,90
8,109,Arjun Rao,27,Male,Hyderabad,Python,72.0,Yes,82
9,110,Sneha Joshi,21,Female,Mumbai,Machine Learning,NaN,No,55
10,111,Karan Patel,29,Male,Pune,Data Science,95.0,Yes,97
11,112,Divya Singh,24,Female,Chennai,Python,61.0,Yes,74
12,113,Anil Kumar,23,Male,Delhi,Machine Learning,79.0,Yes,88
13,114,Pooja Reddy,25,Female,Hyderabad,Data Science,50.0,No,65
14,115,Raj Malhotra,30,Male,Mumbai,Python,84.0,Yes,93
15,116,Anjali Iyer,22,Female,Bangalore,Machine Learning,70.0,Yes,80
16,117,Suresh Tiwari,26,Male,Pune,Data Science,NaN,Yes,77
17,118,Kavya Menon,23,Female,Chennai,Python,88.0,Yes,91
18,119,Vikram Bose,28,Male,Delhi,Machine Learning,63.0,Yes,70
19,120,Ritika Shah,24,Female,Mumbai,Data Science,77.0,Yes,86

In [13]:
col1 = df["Name"]
type(col1)

pandas.Series

In [14]:
df['Course']

0               Python
1         Data Science
2               Python
3     Machine Learning
4         Data Science
5               Python
6     Machine Learning
7         Data Science
8               Python
9     Machine Learning
10        Data Science
11              Python
12    Machine Learning
13        Data Science
14              Python
15    Machine Learning
16        Data Science
17              Python
18    Machine Learning
19        Data Science
Name: Course, dtype: str

In [15]:
# Select multiple columns
data1 = df[["Name", "Marks", "Gender"]]
data1

             Name  Marks  Gender
0        Ali Khan   88.0    Male
1      Sara Mehta   92.0     NaN
2    John D'souza   55.0    Male
3      Mia Sharma   76.0  Female
4     Rahul Verma   45.0    Male
5      Priya Nair   91.0  Female
6      Tom Wilson   67.0    Male
7      Neha Gupta   83.0  Female
8       Arjun Rao   72.0    Male
9     Sneha Joshi    NaN  Female
10    Karan Patel   95.0    Male
11    Divya Singh   61.0  Female
12     Anil Kumar   79.0    Male
13    Pooja Reddy   50.0  Female
14   Raj Malhotra   84.0    Male
15    Anjali Iyer   70.0  Female
16  Suresh Tiwari    NaN    Male
17    Kavya Menon   88.0  Female
18    Vikram Bose   63.0    Male
19    Ritika Shah   77.0  Female

In [16]:
# loc - select data by label
df.loc[0]
df.loc[1:3]
df.loc[3, "Name"]
df.loc[3, ["Name", "City"]]
df.loc[1:5, ["Name", "City", "Marks"]]

           Name       City  Marks
1    Sara Mehta      Delhi   92.0
2  John D'souza  Bangalore   55.0
3    Mia Sharma     Mumbai   76.0
4   Rahul Verma       Pune   45.0
5    Priya Nair    Chennai   91.0

In [17]:
# iloc - select by position
df.iloc[0]
df.iloc[2:6]
df.iloc[0, 0]
df.iloc[0, 0:4]
df.iloc[0:4, 1:6]

           Name  Age  Gender       City            Course
0      Ali Khan   22    Male     Mumbai            Python
1    Sara Mehta   25     NaN      Delhi      Data Science
2  John D'souza   21    Male  Bangalore            Python
3    Mia Sharma   28  Female     Mumbai  Machine Learning

In [18]:
# Iterate rows with iterrows() % itertuples()

for index, row in df.iterrows():
    #print(index)
    print(index, row)

0 StudentID          101
Name          Ali Khan
Age                 22
Gender            Male
City            Mumbai
Course          Python
Marks             88.0
Passed             Yes
Attendance          95
Name: 0, dtype: object
1 StudentID              102
Name            Sara Mehta
Age                     25
Gender                 NaN
City                 Delhi
Course        Data Science
Marks                 92.0
Passed                 Yes
Attendance              98
Name: 1, dtype: object
2 StudentID              103
Name          John D'souza
Age                     21
Gender                Male
City             Bangalore
Course              Python
Marks                 55.0
Passed                  No
Attendance              72
Name: 2, dtype: object
3 StudentID                  104
Name                Mia Sharma
Age                         28
Gender                  Female
City                    Mumbai
Course        Machine Learning
Marks                     76.0
Passed                     Yes
Attendance                  85
Name: 3, dtype: object
4 StudentID              105
Name           Rahul Verma
Age                     23
Gender                Male
City                  Pune
Course        Data Science
Marks                 45.0
Passed                  No
Attendance              60
Name: 4, dtype: object
5 StudentID            106
Name          Priya Nair
Age                   26
Gender            Female
City             Chennai
Course            Python
Marks               91.0
Passed               Yes
Attendance            99
Name: 5, dtype: object
6 StudentID                  107
Name                Tom Wilson
Age                         24
Gender                    Male
City                     Delhi
Course        Machine Learning
Marks                     67.0
Passed                     Yes
Attendance                  78
Name: 6, dtype: object
7 StudentID              108
Name            Neha Gupta
Age                     22
Gender              Female
City             Bangalore
Course        Data Science
Marks                 83.0
Passed                 Yes
Attendance              90
Name: 7, dtype: object
8 StudentID           109
Name          Arjun Rao
Age                  27
Gender             Male
City          Hyderabad
Course           Python
Marks              72.0
Passed              Yes
Attendance           82
Name: 8, dtype: object
9 StudentID                  110
Name               Sneha Joshi
Age                         21
Gender                  Female
City                    Mumbai
Course        Machine Learning
Marks                      NaN
Passed                      No
Attendance                  55
Name: 9, dtype: object
10 StudentID              111
Name           Karan Patel
Age                     29
Gender                Male
City                  Pune
Course        Data Science
Marks                 95.0
Passed                 Yes
Attendance              97
Name: 10, dtype: object
11 StudentID             112
Name          Divya Singh
Age                    24
Gender             Female
City              Chennai
Course             Python
Marks                61.0
Passed                Yes
Attendance             74
Name: 11, dtype: object
12 StudentID                  113
Name                Anil Kumar
Age                         23
Gender                    Male
City                     Delhi
Course        Machine Learning
Marks                     79.0
Passed                     Yes
Attendance                  88
Name: 12, dtype: object
13 StudentID              114
Name           Pooja Reddy
Age                     25
Gender              Female
City             Hyderabad
Course        Data Science
Marks                 50.0
Passed                  No
Attendance              65
Name: 13, dtype: object
14 StudentID              115
Name          Raj Malhotra
Age                     30
Gender                Male
City                Mumbai
Course              Python
Marks                 84.0
Passed                 Yes
Attendance              93
Name: 14, dtype: object
15 StudentID                  116
Name               Anjali Iyer
Age                         22
Gender                  Female
City                 Bangalore
Course        Machine Learning
Marks                     70.0
Passed                     Yes
Attendance                  80
Name: 15, dtype: object
16 StudentID               117
Name          Suresh Tiwari
Age                      26
Gender                 Male
City                   Pune
Course         Data Science
Marks                   NaN
Passed                  Yes
Attendance               77
Name: 16, dtype: object
17 StudentID             118
Name          Kavya Menon
Age                    23
Gender             Female
City              Chennai
Course             Python
Marks                88.0
Passed                Yes
Attendance             91
Name: 17, dtype: object
18 StudentID                  119
Name               Vikram Bose
Age                         28
Gender                    Male
City                     Delhi
Course        Machine Learning
Marks                     63.0
Passed                     Yes
Attendance                  70
Name: 18, dtype: object
19 StudentID              120
Name           Ritika Shah
Age                     24
Gender              Female
City                Mumbai
Course        Data Science
Marks                 77.0
Passed                 Yes
Attendance              86
Name: 19, dtype: object

In [19]:
# itertuples()

for row in df.itertuples():
    print(row.Index, row.StudentID, row.Name, row.Marks)

0 101 Ali Khan 88.0
1 102 Sara Mehta 92.0
2 103 John D'souza 55.0
3 104 Mia Sharma 76.0
4 105 Rahul Verma 45.0
5 106 Priya Nair 91.0
6 107 Tom Wilson 67.0
7 108 Neha Gupta 83.0
8 109 Arjun Rao 72.0
9 110 Sneha Joshi nan
10 111 Karan Patel 95.0
11 112 Divya Singh 61.0
12 113 Anil Kumar 79.0
13 114 Pooja Reddy 50.0
14 115 Raj Malhotra 84.0
15 116 Anjali Iyer 70.0
16 117 Suresh Tiwari nan
17 118 Kavya Menon 88.0
18 119 Vikram Bose 63.0
19 120 Ritika Shah 77.0

### FILTERING DATA

In [20]:
# Filter with one condition

df = pd.read_csv("./data_f/students.csv")
df

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance
0,101,Ali Khan,22,Male,Mumbai,Python,88.0,Yes,95
1,102,Sara Mehta,25,NaN,Delhi,Data Science,92.0,Yes,98
2,103,John D'souza,21,Male,Bangalore,Python,55.0,No,72
3,104,Mia Sharma,28,Female,Mumbai,Machine Learning,76.0,Yes,85
4,105,Rahul Verma,23,Male,Pune,Data Science,45.0,No,60
5,106,Priya Nair,26,Female,Chennai,Python,91.0,Yes,99
6,107,Tom Wilson,24,Male,Delhi,Machine Learning,67.0,Yes,78
7,108,Neha Gupta,22,Female,Bangalore,Data Science,83.0,Yes,90
8,109,Arjun Rao,27,Male,Hyderabad,Python,72.0,Yes,82
9,110,Sneha Joshi,21,Female,Mumbai,Machine Learning,NaN,No,55
10,111,Karan Patel,29,Male,Pune,Data Science,95.0,Yes,97
11,112,Divya Singh,24,Female,Chennai,Python,61.0,Yes,74
12,113,Anil Kumar,23,Male,Delhi,Machine Learning,79.0,Yes,88
13,114,Pooja Reddy,25,Female,Hyderabad,Data Science,50.0,No,65
14,115,Raj Malhotra,30,Male,Mumbai,Python,84.0,Yes,93
15,116,Anjali Iyer,22,Female,Bangalore,Machine Learning,70.0,Yes,80
16,117,Suresh Tiwari,26,Male,Pune,Data Science,NaN,Yes,77
17,118,Kavya Menon,23,Female,Chennai,Python,88.0,Yes,91
18,119,Vikram Bose,28,Male,Delhi,Machine Learning,63.0,Yes,70
19,120,Ritika Shah,24,Female,Mumbai,Data Science,77.0,Yes,86

In [21]:
# Filter with one condition

filtered = df[df["Marks"] >= 90]
filtered

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance
1,102,Sara Mehta,25,NaN,Delhi,Data Science,92.0,Yes,98
5,106,Priya Nair,26,Female,Chennai,Python,91.0,Yes,99
10,111,Karan Patel,29,Male,Pune,Data Science,95.0,Yes,97

In [22]:
# Filter with multiple condition

df[(df["Marks"] >= 80) & (df["Age"] > 25)]

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance
5,106,Priya Nair,26,Female,Chennai,Python,91.0,Yes,99
10,111,Karan Patel,29,Male,Pune,Data Science,95.0,Yes,97
14,115,Raj Malhotra,30,Male,Mumbai,Python,84.0,Yes,93

In [23]:
# isin() - filter from a list

names = ["Pooja Reddy", "Ritika Shah", "Ali Khan", "John D'souza"]
df[df["Name"].isin(names)]

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance
0,101,Ali Khan,22,Male,Mumbai,Python,88.0,Yes,95
2,103,John D'souza,21,Male,Bangalore,Python,55.0,No,72
13,114,Pooja Reddy,25,Female,Hyderabad,Data Science,50.0,No,65
19,120,Ritika Shah,24,Female,Mumbai,Data Science,77.0,Yes,86

In [24]:
# query() - filter using plain text

df.query("Marks >= 90")

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance
1,102,Sara Mehta,25,NaN,Delhi,Data Science,92.0,Yes,98
5,106,Priya Nair,26,Female,Chennai,Python,91.0,Yes,99
10,111,Karan Patel,29,Male,Pune,Data Science,95.0,Yes,97

In [25]:
df.query("Marks >= 90 and Age >=25")

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance
1,102,Sara Mehta,25,NaN,Delhi,Data Science,92.0,Yes,98
5,106,Priya Nair,26,Female,Chennai,Python,91.0,Yes,99
10,111,Karan Patel,29,Male,Pune,Data Science,95.0,Yes,97

In [26]:
mark_val = 90
df.query("Marks >= @mark_val")

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance
1,102,Sara Mehta,25,NaN,Delhi,Data Science,92.0,Yes,98
5,106,Priya Nair,26,Female,Chennai,Python,91.0,Yes,99
10,111,Karan Patel,29,Male,Pune,Data Science,95.0,Yes,97

### ADDING & MODIFYING COLUMNS

In [27]:

df = pd.read_csv("./data_f/students.csv")

In [28]:
# Add a new column
df["is_Scholarship_Eligible"] = df["Marks"] >= 90
df

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance,is_Scholarship_Eligible
0,101,Ali Khan,22,Male,Mumbai,Python,88.0,Yes,95,False
1,102,Sara Mehta,25,NaN,Delhi,Data Science,92.0,Yes,98,True
2,103,John D'souza,21,Male,Bangalore,Python,55.0,No,72,False
3,104,Mia Sharma,28,Female,Mumbai,Machine Learning,76.0,Yes,85,False
4,105,Rahul Verma,23,Male,Pune,Data Science,45.0,No,60,False
5,106,Priya Nair,26,Female,Chennai,Python,91.0,Yes,99,True
6,107,Tom Wilson,24,Male,Delhi,Machine Learning,67.0,Yes,78,False
7,108,Neha Gupta,22,Female,Bangalore,Data Science,83.0,Yes,90,False
8,109,Arjun Rao,27,Male,Hyderabad,Python,72.0,Yes,82,False
9,110,Sneha Joshi,21,Female,Mumbai,Machine Learning,NaN,No,55,False
10,111,Karan Patel,29,Male,Pune,Data Science,95.0,Yes,97,True
11,112,Divya Singh,24,Female,Chennai,Python,61.0,Yes,74,False
12,113,Anil Kumar,23,Male,Delhi,Machine Learning,79.0,Yes,88,False
13,114,Pooja Reddy,25,Female,Hyderabad,Data Science,50.0,No,65,False
14,115,Raj Malhotra,30,Male,Mumbai,Python,84.0,Yes,93,False
15,116,Anjali Iyer,22,Female,Bangalore,Machine Learning,70.0,Yes,80,False
16,117,Suresh Tiwari,26,Male,Pune,Data Science,NaN,Yes,77,False
17,118,Kavya Menon,23,Female,Chennai,Python,88.0,Yes,91,False
18,119,Vikram Bose,28,Male,Delhi,Machine Learning,63.0,Yes,70,False
19,120,Ritika Shah,24,Female,Mumbai,Data Science,77.0,Yes,86,False

In [29]:
# Modifying an existing column
df["Marks"] = df["Marks"] + 2
df

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance,is_Scholarship_Eligible
0,101,Ali Khan,22,Male,Mumbai,Python,90.0,Yes,95,False
1,102,Sara Mehta,25,NaN,Delhi,Data Science,94.0,Yes,98,True
2,103,John D'souza,21,Male,Bangalore,Python,57.0,No,72,False
3,104,Mia Sharma,28,Female,Mumbai,Machine Learning,78.0,Yes,85,False
4,105,Rahul Verma,23,Male,Pune,Data Science,47.0,No,60,False
5,106,Priya Nair,26,Female,Chennai,Python,93.0,Yes,99,True
6,107,Tom Wilson,24,Male,Delhi,Machine Learning,69.0,Yes,78,False
7,108,Neha Gupta,22,Female,Bangalore,Data Science,85.0,Yes,90,False
8,109,Arjun Rao,27,Male,Hyderabad,Python,74.0,Yes,82,False
9,110,Sneha Joshi,21,Female,Mumbai,Machine Learning,NaN,No,55,False
10,111,Karan Patel,29,Male,Pune,Data Science,97.0,Yes,97,True
11,112,Divya Singh,24,Female,Chennai,Python,63.0,Yes,74,False
12,113,Anil Kumar,23,Male,Delhi,Machine Learning,81.0,Yes,88,False
13,114,Pooja Reddy,25,Female,Hyderabad,Data Science,52.0,No,65,False
14,115,Raj Malhotra,30,Male,Mumbai,Python,86.0,Yes,93,False
15,116,Anjali Iyer,22,Female,Bangalore,Machine Learning,72.0,Yes,80,False
16,117,Suresh Tiwari,26,Male,Pune,Data Science,NaN,Yes,77,False
17,118,Kavya Menon,23,Female,Chennai,Python,90.0,Yes,91,False
18,119,Vikram Bose,28,Male,Delhi,Machine Learning,65.0,Yes,70,False
19,120,Ritika Shah,24,Female,Mumbai,Data Science,79.0,Yes,86,False

In [30]:
# apply() - custom logic per row
def get_grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    else:
        return "C"

df["Grade"] = df["Marks"].apply(get_grade)
df

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance,is_Scholarship_Eligible,Grade
0,101,Ali Khan,22,Male,Mumbai,Python,90.0,Yes,95,False,A
1,102,Sara Mehta,25,NaN,Delhi,Data Science,94.0,Yes,98,True,A
2,103,John D'souza,21,Male,Bangalore,Python,57.0,No,72,False,C
3,104,Mia Sharma,28,Female,Mumbai,Machine Learning,78.0,Yes,85,False,C
4,105,Rahul Verma,23,Male,Pune,Data Science,47.0,No,60,False,C
5,106,Priya Nair,26,Female,Chennai,Python,93.0,Yes,99,True,A
6,107,Tom Wilson,24,Male,Delhi,Machine Learning,69.0,Yes,78,False,C
7,108,Neha Gupta,22,Female,Bangalore,Data Science,85.0,Yes,90,False,B
8,109,Arjun Rao,27,Male,Hyderabad,Python,74.0,Yes,82,False,C
9,110,Sneha Joshi,21,Female,Mumbai,Machine Learning,NaN,No,55,False,C
10,111,Karan Patel,29,Male,Pune,Data Science,97.0,Yes,97,True,A
11,112,Divya Singh,24,Female,Chennai,Python,63.0,Yes,74,False,C
12,113,Anil Kumar,23,Male,Delhi,Machine Learning,81.0,Yes,88,False,B
13,114,Pooja Reddy,25,Female,Hyderabad,Data Science,52.0,No,65,False,C
14,115,Raj Malhotra,30,Male,Mumbai,Python,86.0,Yes,93,False,B
15,116,Anjali Iyer,22,Female,Bangalore,Machine Learning,72.0,Yes,80,False,C
16,117,Suresh Tiwari,26,Male,Pune,Data Science,NaN,Yes,77,False,C
17,118,Kavya Menon,23,Female,Chennai,Python,90.0,Yes,91,False,A
18,119,Vikram Bose,28,Male,Delhi,Machine Learning,65.0,Yes,70,False,C
19,120,Ritika Shah,24,Female,Mumbai,Data Science,79.0,Yes,86,False,C

### HANDLING MISSING DATA

In [31]:
df = pd.read_csv("./data_f/students.csv")
df

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance
0,101,Ali Khan,22,Male,Mumbai,Python,88.0,Yes,95
1,102,Sara Mehta,25,NaN,Delhi,Data Science,92.0,Yes,98
2,103,John D'souza,21,Male,Bangalore,Python,55.0,No,72
3,104,Mia Sharma,28,Female,Mumbai,Machine Learning,76.0,Yes,85
4,105,Rahul Verma,23,Male,Pune,Data Science,45.0,No,60
5,106,Priya Nair,26,Female,Chennai,Python,91.0,Yes,99
6,107,Tom Wilson,24,Male,Delhi,Machine Learning,67.0,Yes,78
7,108,Neha Gupta,22,Female,Bangalore,Data Science,83.0,Yes,90
8,109,Arjun Rao,27,Male,Hyderabad,Python,72.0,Yes,82
9,110,Sneha Joshi,21,Female,Mumbai,Machine Learning,NaN,No,55
10,111,Karan Patel,29,Male,Pune,Data Science,95.0,Yes,97
11,112,Divya Singh,24,Female,Chennai,Python,61.0,Yes,74
12,113,Anil Kumar,23,Male,Delhi,Machine Learning,79.0,Yes,88
13,114,Pooja Reddy,25,Female,Hyderabad,Data Science,50.0,No,65
14,115,Raj Malhotra,30,Male,Mumbai,Python,84.0,Yes,93
15,116,Anjali Iyer,22,Female,Bangalore,Machine Learning,70.0,Yes,80
16,117,Suresh Tiwari,26,Male,Pune,Data Science,NaN,Yes,77
17,118,Kavya Menon,23,Female,Chennai,Python,88.0,Yes,91
18,119,Vikram Bose,28,Male,Delhi,Machine Learning,63.0,Yes,70
19,120,Ritika Shah,24,Female,Mumbai,Data Science,77.0,Yes,86

In [32]:
# Detect missing values
df.isnull().sum()

StudentID     0
Name          0
Age           0
Gender        1
City          0
Course        0
Marks         2
Passed        0
Attendance    0
dtype: int64

In [33]:
# Fill missing values - fillna()
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())
df

df["Gender"] = df["Gender"].fillna("Female")
df

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance
0,101,Ali Khan,22,Male,Mumbai,Python,88.000000,Yes,95
1,102,Sara Mehta,25,Female,Delhi,Data Science,92.000000,Yes,98
2,103,John D'souza,21,Male,Bangalore,Python,55.000000,No,72
3,104,Mia Sharma,28,Female,Mumbai,Machine Learning,76.000000,Yes,85
4,105,Rahul Verma,23,Male,Pune,Data Science,45.000000,No,60
5,106,Priya Nair,26,Female,Chennai,Python,91.000000,Yes,99
6,107,Tom Wilson,24,Male,Delhi,Machine Learning,67.000000,Yes,78
7,108,Neha Gupta,22,Female,Bangalore,Data Science,83.000000,Yes,90
8,109,Arjun Rao,27,Male,Hyderabad,Python,72.000000,Yes,82
9,110,Sneha Joshi,21,Female,Mumbai,Machine Learning,74.222222,No,55
10,111,Karan Patel,29,Male,Pune,Data Science,95.000000,Yes,97
11,112,Divya Singh,24,Female,Chennai,Python,61.000000,Yes,74
12,113,Anil Kumar,23,Male,Delhi,Machine Learning,79.000000,Yes,88
13,114,Pooja Reddy,25,Female,Hyderabad,Data Science,50.000000,No,65
14,115,Raj Malhotra,30,Male,Mumbai,Python,84.000000,Yes,93
15,116,Anjali Iyer,22,Female,Bangalore,Machine Learning,70.000000,Yes,80
16,117,Suresh Tiwari,26,Male,Pune,Data Science,74.222222,Yes,77
17,118,Kavya Menon,23,Female,Chennai,Python,88.000000,Yes,91
18,119,Vikram Bose,28,Male,Delhi,Machine Learning,63.000000,Yes,70
19,120,Ritika Shah,24,Female,Mumbai,Data Science,77.000000,Yes,86

In [34]:
# Drop missing rows - dropna()

df_students = pd.read_csv("./data_f/students.csv")
df_students

df_clean =df_students.dropna()
df_clean

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance
0,101,Ali Khan,22,Male,Mumbai,Python,88.0,Yes,95
2,103,John D'souza,21,Male,Bangalore,Python,55.0,No,72
3,104,Mia Sharma,28,Female,Mumbai,Machine Learning,76.0,Yes,85
4,105,Rahul Verma,23,Male,Pune,Data Science,45.0,No,60
5,106,Priya Nair,26,Female,Chennai,Python,91.0,Yes,99
6,107,Tom Wilson,24,Male,Delhi,Machine Learning,67.0,Yes,78
7,108,Neha Gupta,22,Female,Bangalore,Data Science,83.0,Yes,90
8,109,Arjun Rao,27,Male,Hyderabad,Python,72.0,Yes,82
10,111,Karan Patel,29,Male,Pune,Data Science,95.0,Yes,97
11,112,Divya Singh,24,Female,Chennai,Python,61.0,Yes,74
12,113,Anil Kumar,23,Male,Delhi,Machine Learning,79.0,Yes,88
13,114,Pooja Reddy,25,Female,Hyderabad,Data Science,50.0,No,65
14,115,Raj Malhotra,30,Male,Mumbai,Python,84.0,Yes,93
15,116,Anjali Iyer,22,Female,Bangalore,Machine Learning,70.0,Yes,80
17,118,Kavya Menon,23,Female,Chennai,Python,88.0,Yes,91
18,119,Vikram Bose,28,Male,Delhi,Machine Learning,63.0,Yes,70
19,120,Ritika Shah,24,Female,Mumbai,Data Science,77.0,Yes,86

### SORTING DATA

In [35]:
df = pd.read_csv("./data_f/students.csv")
df

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance
0,101,Ali Khan,22,Male,Mumbai,Python,88.0,Yes,95
1,102,Sara Mehta,25,NaN,Delhi,Data Science,92.0,Yes,98
2,103,John D'souza,21,Male,Bangalore,Python,55.0,No,72
3,104,Mia Sharma,28,Female,Mumbai,Machine Learning,76.0,Yes,85
4,105,Rahul Verma,23,Male,Pune,Data Science,45.0,No,60
5,106,Priya Nair,26,Female,Chennai,Python,91.0,Yes,99
6,107,Tom Wilson,24,Male,Delhi,Machine Learning,67.0,Yes,78
7,108,Neha Gupta,22,Female,Bangalore,Data Science,83.0,Yes,90
8,109,Arjun Rao,27,Male,Hyderabad,Python,72.0,Yes,82
9,110,Sneha Joshi,21,Female,Mumbai,Machine Learning,NaN,No,55
10,111,Karan Patel,29,Male,Pune,Data Science,95.0,Yes,97
11,112,Divya Singh,24,Female,Chennai,Python,61.0,Yes,74
12,113,Anil Kumar,23,Male,Delhi,Machine Learning,79.0,Yes,88
13,114,Pooja Reddy,25,Female,Hyderabad,Data Science,50.0,No,65
14,115,Raj Malhotra,30,Male,Mumbai,Python,84.0,Yes,93
15,116,Anjali Iyer,22,Female,Bangalore,Machine Learning,70.0,Yes,80
16,117,Suresh Tiwari,26,Male,Pune,Data Science,NaN,Yes,77
17,118,Kavya Menon,23,Female,Chennai,Python,88.0,Yes,91
18,119,Vikram Bose,28,Male,Delhi,Machine Learning,63.0,Yes,70
19,120,Ritika Shah,24,Female,Mumbai,Data Science,77.0,Yes,86

In [36]:
# Sort by one column
sorted_df = df.sort_values("Marks", ascending=False)
sorted_df

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance
10,111,Karan Patel,29,Male,Pune,Data Science,95.0,Yes,97
1,102,Sara Mehta,25,NaN,Delhi,Data Science,92.0,Yes,98
5,106,Priya Nair,26,Female,Chennai,Python,91.0,Yes,99
0,101,Ali Khan,22,Male,Mumbai,Python,88.0,Yes,95
17,118,Kavya Menon,23,Female,Chennai,Python,88.0,Yes,91
14,115,Raj Malhotra,30,Male,Mumbai,Python,84.0,Yes,93
7,108,Neha Gupta,22,Female,Bangalore,Data Science,83.0,Yes,90
12,113,Anil Kumar,23,Male,Delhi,Machine Learning,79.0,Yes,88
19,120,Ritika Shah,24,Female,Mumbai,Data Science,77.0,Yes,86
3,104,Mia Sharma,28,Female,Mumbai,Machine Learning,76.0,Yes,85
8,109,Arjun Rao,27,Male,Hyderabad,Python,72.0,Yes,82
15,116,Anjali Iyer,22,Female,Bangalore,Machine Learning,70.0,Yes,80
6,107,Tom Wilson,24,Male,Delhi,Machine Learning,67.0,Yes,78
18,119,Vikram Bose,28,Male,Delhi,Machine Learning,63.0,Yes,70
11,112,Divya Singh,24,Female,Chennai,Python,61.0,Yes,74
2,103,John D'souza,21,Male,Bangalore,Python,55.0,No,72
13,114,Pooja Reddy,25,Female,Hyderabad,Data Science,50.0,No,65
4,105,Rahul Verma,23,Male,Pune,Data Science,45.0,No,60
9,110,Sneha Joshi,21,Female,Mumbai,Machine Learning,NaN,No,55
16,117,Suresh Tiwari,26,Male,Pune,Data Science,NaN,Yes,77

In [37]:
# Sorting by multiple columns
df
sorted_df1 = df.sort_values(["Course", "Marks"],    ascending=[True, False])
sorted_df1

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance
10,111,Karan Patel,29,Male,Pune,Data Science,95.0,Yes,97
1,102,Sara Mehta,25,NaN,Delhi,Data Science,92.0,Yes,98
7,108,Neha Gupta,22,Female,Bangalore,Data Science,83.0,Yes,90
19,120,Ritika Shah,24,Female,Mumbai,Data Science,77.0,Yes,86
13,114,Pooja Reddy,25,Female,Hyderabad,Data Science,50.0,No,65
4,105,Rahul Verma,23,Male,Pune,Data Science,45.0,No,60
16,117,Suresh Tiwari,26,Male,Pune,Data Science,NaN,Yes,77
12,113,Anil Kumar,23,Male,Delhi,Machine Learning,79.0,Yes,88
3,104,Mia Sharma,28,Female,Mumbai,Machine Learning,76.0,Yes,85
15,116,Anjali Iyer,22,Female,Bangalore,Machine Learning,70.0,Yes,80
6,107,Tom Wilson,24,Male,Delhi,Machine Learning,67.0,Yes,78
18,119,Vikram Bose,28,Male,Delhi,Machine Learning,63.0,Yes,70
9,110,Sneha Joshi,21,Female,Mumbai,Machine Learning,NaN,No,55
5,106,Priya Nair,26,Female,Chennai,Python,91.0,Yes,99
0,101,Ali Khan,22,Male,Mumbai,Python,88.0,Yes,95
17,118,Kavya Menon,23,Female,Chennai,Python,88.0,Yes,91
14,115,Raj Malhotra,30,Male,Mumbai,Python,84.0,Yes,93
8,109,Arjun Rao,27,Male,Hyderabad,Python,72.0,Yes,82
11,112,Divya Singh,24,Female,Chennai,Python,61.0,Yes,74
2,103,John D'souza,21,Male,Bangalore,Python,55.0,No,72

### GROUPBY & AGGREGATION

In [38]:
df = pd.read_csv("./data_f/students.csv")
df

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance
0,101,Ali Khan,22,Male,Mumbai,Python,88.0,Yes,95
1,102,Sara Mehta,25,NaN,Delhi,Data Science,92.0,Yes,98
2,103,John D'souza,21,Male,Bangalore,Python,55.0,No,72
3,104,Mia Sharma,28,Female,Mumbai,Machine Learning,76.0,Yes,85
4,105,Rahul Verma,23,Male,Pune,Data Science,45.0,No,60
5,106,Priya Nair,26,Female,Chennai,Python,91.0,Yes,99
6,107,Tom Wilson,24,Male,Delhi,Machine Learning,67.0,Yes,78
7,108,Neha Gupta,22,Female,Bangalore,Data Science,83.0,Yes,90
8,109,Arjun Rao,27,Male,Hyderabad,Python,72.0,Yes,82
9,110,Sneha Joshi,21,Female,Mumbai,Machine Learning,NaN,No,55
10,111,Karan Patel,29,Male,Pune,Data Science,95.0,Yes,97
11,112,Divya Singh,24,Female,Chennai,Python,61.0,Yes,74
12,113,Anil Kumar,23,Male,Delhi,Machine Learning,79.0,Yes,88
13,114,Pooja Reddy,25,Female,Hyderabad,Data Science,50.0,No,65
14,115,Raj Malhotra,30,Male,Mumbai,Python,84.0,Yes,93
15,116,Anjali Iyer,22,Female,Bangalore,Machine Learning,70.0,Yes,80
16,117,Suresh Tiwari,26,Male,Pune,Data Science,NaN,Yes,77
17,118,Kavya Menon,23,Female,Chennai,Python,88.0,Yes,91
18,119,Vikram Bose,28,Male,Delhi,Machine Learning,63.0,Yes,70
19,120,Ritika Shah,24,Female,Mumbai,Data Science,77.0,Yes,86

In [39]:
# Basic Groupby
mean_values = df.groupby("Course")["Marks"].mean()
mean_values

Course
Data Science        73.666667
Machine Learning    71.000000
Python              77.000000
Name: Marks, dtype: float64

In [40]:
max_values = df.groupby("Course")["Marks"].max()
max_values

Course
Data Science        95.0
Machine Learning    79.0
Python              91.0
Name: Marks, dtype: float64

In [41]:
min_values = df.groupby("Course")["Marks"].min()
min_values

Course
Data Science        45.0
Machine Learning    63.0
Python              55.0
Name: Marks, dtype: float64

In [42]:
# multiple aggregation with agg()

results = df.groupby("Course")["Marks"].agg(["mean","max","min", "count"])
results

                       mean   max   min  count
Course
Data Science      73.666667  95.0  45.0      6
Machine Learning  71.000000  79.0  63.0      5
Python            77.000000  91.0  55.0      7

In [43]:
results2 = df.groupby("Course")["Attendance"].agg(["mean","max","min", "count"])
results2

                       mean  max  min  count
Course
Data Science      81.857143   98   60      7
Machine Learning  76.000000   88   55      6
Python            86.571429   99   72      7

### MERGING & JOINING DATAFRAMES

In [44]:

students = pd.DataFrame({
    "ID": [1,2,3],
    "Name": ["Nor", "Fatin", "Nabila"]
})
display(students)

scores = pd.DataFrame({
    "ID": [1,2,4],
    "Scores": [85,92,78]
})
display(scores)

   ID    Name
0   1     Nor
1   2   Fatin
2   3  Nabila

   ID  Scores
0   1      85
1   2      92
2   4      78

In [45]:
# Inner join - keep only matches

results = pd.merge(students, scores, on="ID", how="inner")
results

   ID   Name  Scores
0   1    Nor      85
1   2  Fatin      92

In [46]:
# Left join - keep all left rows

results2 = pd.merge(students, scores, on="ID", how="left")
results2

   ID    Name  Scores
0   1     Nor    85.0
1   2   Fatin    92.0
2   3  Nabila     NaN

In [47]:
# Right join - keep all the right rows
results3 = pd.merge(students, scores, on="ID", how="right")
results3

   ID   Name  Scores
0   1    Nor      85
1   2  Fatin      92
2   4    NaN      78

In [48]:
# Outer join - keep every row from both Table
results4 = pd.merge(students, scores, on="ID", how="outer")
results4

   ID    Name  Scores
0   1     Nor    85.0
1   2   Fatin    92.0
2   3  Nabila     NaN
3   4     NaN    78.0

### SUMMARY STATISTIC

In [49]:
df = pd.read_csv("./data_f/students.csv")
df

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance
0,101,Ali Khan,22,Male,Mumbai,Python,88.0,Yes,95
1,102,Sara Mehta,25,NaN,Delhi,Data Science,92.0,Yes,98
2,103,John D'souza,21,Male,Bangalore,Python,55.0,No,72
3,104,Mia Sharma,28,Female,Mumbai,Machine Learning,76.0,Yes,85
4,105,Rahul Verma,23,Male,Pune,Data Science,45.0,No,60
5,106,Priya Nair,26,Female,Chennai,Python,91.0,Yes,99
6,107,Tom Wilson,24,Male,Delhi,Machine Learning,67.0,Yes,78
7,108,Neha Gupta,22,Female,Bangalore,Data Science,83.0,Yes,90
8,109,Arjun Rao,27,Male,Hyderabad,Python,72.0,Yes,82
9,110,Sneha Joshi,21,Female,Mumbai,Machine Learning,NaN,No,55
10,111,Karan Patel,29,Male,Pune,Data Science,95.0,Yes,97
11,112,Divya Singh,24,Female,Chennai,Python,61.0,Yes,74
12,113,Anil Kumar,23,Male,Delhi,Machine Learning,79.0,Yes,88
13,114,Pooja Reddy,25,Female,Hyderabad,Data Science,50.0,No,65
14,115,Raj Malhotra,30,Male,Mumbai,Python,84.0,Yes,93
15,116,Anjali Iyer,22,Female,Bangalore,Machine Learning,70.0,Yes,80
16,117,Suresh Tiwari,26,Male,Pune,Data Science,NaN,Yes,77
17,118,Kavya Menon,23,Female,Chennai,Python,88.0,Yes,91
18,119,Vikram Bose,28,Male,Delhi,Machine Learning,63.0,Yes,70
19,120,Ritika Shah,24,Female,Mumbai,Data Science,77.0,Yes,86

In [61]:
# describe() - full summary
results = df.describe()
results["Age"]

count    20.000000
mean     24.650000
std       2.680829
min      21.000000
25%      22.750000
50%      24.000000
75%      26.250000
max      30.000000
Name: Age, dtype: float64

In [60]:
# Individual statistic
print("Count: ",df["Marks"].count())
print("Mean: ", df["Marks"].mean())
print("Std Dev: ", df["Marks"].std())
print("Min val: ", df["Age"].min())
print("Max val: ", df["Age"].max())
print("Sum: ", df["Attendance"].sum())

Count:  18
Mean:  74.22222222222223
Std Dev:  14.953085676268628
Min val:  21
Max val:  30
Sum:  1635

EXTRAS - VALUE_COUNTS/STR/RENAME

In [62]:
df = pd.read_csv("./data_f/students.csv")
df

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance
0,101,Ali Khan,22,Male,Mumbai,Python,88.0,Yes,95
1,102,Sara Mehta,25,NaN,Delhi,Data Science,92.0,Yes,98
2,103,John D'souza,21,Male,Bangalore,Python,55.0,No,72
3,104,Mia Sharma,28,Female,Mumbai,Machine Learning,76.0,Yes,85
4,105,Rahul Verma,23,Male,Pune,Data Science,45.0,No,60
5,106,Priya Nair,26,Female,Chennai,Python,91.0,Yes,99
6,107,Tom Wilson,24,Male,Delhi,Machine Learning,67.0,Yes,78
7,108,Neha Gupta,22,Female,Bangalore,Data Science,83.0,Yes,90
8,109,Arjun Rao,27,Male,Hyderabad,Python,72.0,Yes,82
9,110,Sneha Joshi,21,Female,Mumbai,Machine Learning,NaN,No,55
10,111,Karan Patel,29,Male,Pune,Data Science,95.0,Yes,97
11,112,Divya Singh,24,Female,Chennai,Python,61.0,Yes,74
12,113,Anil Kumar,23,Male,Delhi,Machine Learning,79.0,Yes,88
13,114,Pooja Reddy,25,Female,Hyderabad,Data Science,50.0,No,65
14,115,Raj Malhotra,30,Male,Mumbai,Python,84.0,Yes,93
15,116,Anjali Iyer,22,Female,Bangalore,Machine Learning,70.0,Yes,80
16,117,Suresh Tiwari,26,Male,Pune,Data Science,NaN,Yes,77
17,118,Kavya Menon,23,Female,Chennai,Python,88.0,Yes,91
18,119,Vikram Bose,28,Male,Delhi,Machine Learning,63.0,Yes,70
19,120,Ritika Shah,24,Female,Mumbai,Data Science,77.0,Yes,86

In [66]:
# value_counts()
df["Course"].value_counts()

Course
Python              7
Data Science        7
Machine Learning    6
Name: count, dtype: int64

In [67]:
# String operation with .str
df["Name"].str.upper()

0          ALI KHAN
1        SARA MEHTA
2      JOHN D'SOUZA
3        MIA SHARMA
4       RAHUL VERMA
5        PRIYA NAIR
6        TOM WILSON
7        NEHA GUPTA
8         ARJUN RAO
9       SNEHA JOSHI
10      KARAN PATEL
11      DIVYA SINGH
12       ANIL KUMAR
13      POOJA REDDY
14     RAJ MALHOTRA
15      ANJALI IYER
16    SURESH TIWARI
17      KAVYA MENON
18      VIKRAM BOSE
19      RITIKA SHAH
Name: Name, dtype: str

In [68]:
df["Name"].str.startswith("A")

0      True
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9     False
10    False
11    False
12     True
13    False
14    False
15     True
16    False
17    False
18    False
19    False
Name: Name, dtype: bool

In [71]:
# rename() columns
df_new = df.rename(columns={
    "Marks": "Scores",
    "Name": "Student"
})
df_new

df_new.columns.tolist()

['StudentID',
 'Student',
 'Age',
 'Gender',
 'City',
 'Course',
 'Scores',
 'Passed',
 'Attendance']